import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import Chakra from "@/components/Chakra/Chakra";
import Downtime from '@/components/Downtime/Downtime';
import { globalConfig } from "@/constants";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: globalConfig.TITLE_PROJECT,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" style={{overflowY: "hidden"}}>
      <body className={`${inter.className} overflow-hidden h-screen min-h-screen`}>
        <main className="w-full bg-white h-full">
          <SessionAuthProvider>
            <Chakra>
              <Downtime /> 
              {children}
            </Chakra>
          </SessionAuthProvider>
        </main>
      </body>
      <Script
      src="https://kit.fontawesome.com/ec20f55a3f.js" crossOrigin="anonymous"
      ></Script>
     
    </html>
  );
}
