import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import Chakra from "@/components/Chakra/Chakra";
import Downtime from '@/components/Downtime/Downtime';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Liquidate Inventories",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container">
          <SessionAuthProvider>
            <Chakra>
              <Downtime /> 
              {children}
            </Chakra>
          </SessionAuthProvider>
        </main>
      </body>
    </html>
  );
}
